# Generated by Django 3.2.5 on 2021-07-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_title', models.CharField(max_length=64, verbose_name='Название компании')),
                ('place_title', models.CharField(max_length=64, verbose_name='Название заведения')),
                ('address', models.CharField(max_length=256, verbose_name='Фактический адресс')),
                ('payment_details', models.TextField(max_length=512, verbose_name='Реквизиты оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('company', models.ManyToManyField(related_name='companies', to='orderscrm.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_list', models.TextField(max_length=2048, verbose_name='Тело заказа')),
                ('order_sum', models.IntegerField(verbose_name='Сумма заказа')),
                ('offer', models.BooleanField(verbose_name='Коммерческое предложение')),
                ('payment', models.BooleanField(verbose_name='Счет выставлен')),
                ('payment_done', models.BooleanField(verbose_name='Счет оплачен')),
                ('payment_sum', models.IntegerField(verbose_name='Сумма оплаты')),
                ('order_completed', models.BooleanField(verbose_name='Заказ выполнен')),
                ('order_done', models.BooleanField(verbose_name='Заказ сдан')),
                ('posted_at', models.DateField(auto_now_add=True, verbose_name='Дата размещения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orderscrm.company', verbose_name='Компания')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orderscrm.customer', verbose_name='Заказчик')),
            ],
        ),
    ]
